### ISSUE TITLE
Be more efficient with pulls when multiple methods are called in rapid succession 

### ISSUE THREAD

**Issue by blumysden** [newsdev/capital_git#3]
Right now in Adventure, just using pull, read, read_all, etc for a few different things per controller action, I get a trace that looks like this:

```
Started GET "/projects/565392863c67538414000020/embed.json?preview=true" for 127.0.0.1 at 2015-11-23 17:31:55 -0500
Processing by ProjectsController#embed as JSON
  Parameters: {"preview"=>"true", "id"=>"565392863c67538414000020"}
D, [2015-11-23T17:31:55.028901 #33812] DEBUG -- : MONGODB | localhost:27017 | adventure_development.find | STARTED | {"find"=>"projects", "filter"=>{"_id"=>BSON::ObjectId('565392863c67538414000020')}}
D, [2015-11-23T17:31:55.031136 #33812] DEBUG -- : MONGODB | localhost:27017 | adventure_development.find | SUCCEEDED | 0.001826s
I, [2015-11-23T17:31:55.032328 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:55.719723 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:55.720315 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:55.727688 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:55.728194 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
I, [2015-11-23T17:31:55.734071 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:56.413196 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:56.413825 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:56.421776 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:56.422270 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
I, [2015-11-23T17:31:56.427733 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:57.089874 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:57.090589 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:57.098712 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:57.099410 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
I, [2015-11-23T17:31:57.105311 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:57.767140 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:57.767853 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:57.775125 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:57.775618 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
I, [2015-11-23T17:31:57.781516 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:58.436839 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:58.437613 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:58.445340 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:58.446253 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
I, [2015-11-23T17:31:58.452632 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:59.115584 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:59.116230 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:59.123524 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:59.124116 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
I, [2015-11-23T17:31:59.130610 #33812]  INFO -- : Fetching origin into /Users/204906/.rvm/gems/ruby-2.2.2@adventure/gems/capital_git-0.1.6/tmp/adv-ex-sports-photos
I, [2015-11-23T17:31:59.793327 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:59.793893 #33812]  INFO -- : Updated refs/heads/master from 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd to 0f4ab7f07831cc4e42b98165c0120b005d53f028
I, [2015-11-23T17:31:59.801385 #33812]  INFO -- : Fetched refs/remotes/origin/master
I, [2015-11-23T17:31:59.801876 #33812]  INFO -- : Updated refs/heads/master from 0f4ab7f07831cc4e42b98165c0120b005d53f028 to 2dd92c3d314fd9fe03d9a4594a26452aaf12c1dd
```

Must be some way to get around this and speed everything up, yes?

**Comment by albertsun** [comment]
So this hasn't been forgotten. There are a couple of different ways we could structure the code to do this, want to present the options I see for discussion.

The two basic methods I see are to implement either 1) some sort of transaction method where multiple calls are wrapped by a pull at the beginning and potentially a push at the end or 2) some sort of system timer that tracks the times at which pulls and methods get called and calls pull again whenever the time goes over some interval. The first might complicate the API code a bit, the second I worry we will run into more serious cross-platform issues and inconsistencies and be very hard to debug race conditions and etc.

So here are some proposed APIs.

Some form of block syntax? Within the block, one pull! is issued before all statements
and they then don't individually call sync.

```
repo.sync do |r|
  r.list
  r.log
end
```

Or more explicitly

```
repo.start_synced
repo.list
repo.log
repo.end_synced
```

Or

```
tx = repo.get_transaction
tx.list
tx.log
tx.end_transaction
```

Or the system clock option. Have a default config setting.

```
CapitalGit.config.sync_interval = 5s
```

And then, any calls that take place within 5 seconds of a previous pull will not pull again

```
repo.list    # will pull
repo.log     # won't pull
             # wait 5 seconds
repo.list    # will pull
```

@blumysden @samjacoby Thoughts?

**Comment by blumysden** [comment]
I agree that the second option feels potentially buggy.  I like how explicit the first choice is, and I really like the block syntax idea personally.

**Comment by albertsun** [comment]
I like the block syntax the most as well. I've got an, I think, working implementation of it in this branch https://github.com/newsdev/capital_git/tree/local-sync-pull

Pretty much exactly that syntax should work (though the `r` object and the `repo` object are not actually the same object.

Want to try it out or take a look @blumysden @samjacoby before I merge it in to master?

```
repo.sync do |r|
  r.list
  r.log
end
```

**Comment by blumysden** [comment]
Sure.  Will try tomorrow.  Feel free to have a go yourself, @samjacoby, if
you want.

**Comment by samjacoby** [comment]
Tests pass nicely, but when linking it from Adventure, I'm catching some errors while trying to pull in certain repositories. 

``` bash
Sync project Pick My ride
I, [2016-02-26T15:46:12.221432 #20]  INFO -- : Failed to create repository from /usr/src/app/vendor/cache/capital_git/tmp/adventure-production-2016-01-11-pick-my-ride
I, [2016-02-26T15:46:12.222284 #20]  INFO -- : Repository at /usr/src/app/vendor/cache/capital_git/tmp/adventure-production-2016-01-11-pick-my-ride doesn't exist
I, [2016-02-26T15:46:12.222922 #20]  INFO -- : Cloning git@newsdev.ec2.nytimes.com:adventure-production-2016-01-11-pick-my-ride.git (master) into /usr/src/app/vendor/cache/capital_git/tmp/adventure-production-2016-01-11-pick-my-ride
Completed 500 Internal Server Error in 1041ms
** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false

Rugged::OSError (Failed to mmap. Could not write data: Invalid argument):
  app/models/project.rb:77:in `capital_git_repo'
  app/models/project.rb:103:in `local_path'
  app/models/project.rb:52:in `sync'
  app/controllers/projects_controller.rb:261:in `sync_project'
```

When trying to re-add the project (pick-my-ride), I get the following:

``` bash
W, [2016-02-26T15:51:20.666424 #20]  WARN -- : Attempting to connect to a repository that's not defined in configuration.
D, [2016-02-26T15:51:20.669057 #20] DEBUG -- : Setting database local_path to /usr/src/app/vendor/cache/capital_git/tmp
Completed 500 Internal Server Error in 16ms
** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false

NoMethodError (undefined method `gsub' for nil:NilClass):
  app/models/project.rb:77:in `capital_git_repo'
  app/models/project.rb:103:in `local_path'
  app/models/project.rb:52:in `sync'
  app/controllers/projects_controller.rb:261:in `sync_project'
```

Not 100% sure what's going on, but it suggests to me that something in here is changing the way Adventure is interacting with capital git. 

Creating a new repo, etc., works 100%. I'll dig into this a bit when I get a chance, unless you have some smart pointers on where to look @albertsun.

**Comment by albertsun** [comment]
Hm I'm not sure. Those seem to be at a layer of the code that I didn't really change in the pulling and cloning bits. And I don't think the underlying rugged or libgit2 versions should have changed from this either. Will look into it a bit too

**Comment by samjacoby** [comment]
This may have something to do w/ various docker builds I have running, and local capital_git linking, more than anything in the implementation.

**Comment by blumysden** [comment]
I'm not seeing the same problems when I run it, Sam.  Could very well be
something weird like that.  If tests are passing, we can always merge, push
the new gem out, try to upgrade, and then peg the gem to an earlier version
if there's a problem, until we can fix.

Thanks, Albert!

**Comment by albertsun** [comment]
Cool. Releasing this as `v0.2.0` https://github.com/newsdev/capital_git/releases/tag/v0.2.0
